services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/API-Development-Project
      - UPSTASH_REDIS_URL=${rediss://default:AVbMAAIjcDFmYTZiMjBlOTk2OTU0NjdjODlhM2M4MDJjYzRkNWU0OXAxMA@usable-hornet-22220.upstash.io:6379}
      - JWT_ACCESS_SECRET_KEY=${nk%sez5edchanm!/pijbbutf465@@zzxqqa}
      - JWT_REFRESH_SECRET_KEY=${mpcsi001oft!@&489IUY^$*Gis8457+_!!87}
      - JWT_ACCESS_EXPIRE_TIME=15m
      - JWT_REFRESH_EXPIRE_TIME=15d
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
