services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/API-Development-Project
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_ACCESS_EXPIRE_TIME=15m
      - JWT_REFRESH_EXPIRE_TIME=15d
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
